const breakfastDB = [
    {
        id:1,
        name: "Arroz Caldo",
        carbs : 25.0,
        fat : 9.3,
        protein : 8.2,
        calories : 217,
        imgURL : "arroz_caldo.jpg",
        cycling : 55,
        running : 37,
        cleaning : 120
    },
    {
        id:2,
        name: "Champorado",
        carbs : 49.8,
        fat : 0.2,
        protein : 2.5,
        calories : 213,
        imgURL : "champorado.jpg",
        cycling : 48,
        running : 32,
        cleaning : 57
    },
    {
        id:3,
        name: "Corned Beef",
        carbs : 5,
        fat : 5,
        protein : 6,
        calories : 90,
        imgURL : "corned_beef.jpg",
        cycling : 13,
        running : 9,
        cleaning : 33
    },
    {
        id:4,
        name: "Daing na Bangus",
        carbs : 22,
        fat : 6,
        protein : 3,
        calories : 150,
        imgURL : "daing_bangus.jpg",
        cycling : 23,
        running : 15,
        cleaning : 55
    },
    {
        id:5,
        name: "Danggit",
        carbs : 16.1,
        fat : 8.9,
        protein : 2.4,
        calories : 153,
        imgURL : "danggit.jpg",
        cycling : 19,
        running : 12,
        cleaning : 45
    },
    {
        id:6,
        name: "Hotdog",
        carbs : 6.5,
        fat : 6.3,
        protein : 2.8,
        calories : 68,
        imgURL : "hotdog.jpg",
        cycling : 13,
        running : 8,
        cleaning : 27
    },
    {
        id:7,
        name: "Longganisa",
        carbs : 22,
        fat : 2.6,
        protein : 3,
        calories : 116,
        imgURL : "longganisa.jpg",
        cycling : 17,
        running : 11,
        cleaning : 42
    },
    {
        id:8,
        name: "Lugaw Chicken",
        carbs : 34,
        fat : 9,
        protein : 6,
        calories : 240,
        imgURL : "lugaw_chicken.jpg",
        cycling : 36,
        running : 24,
        cleaning : 61
    },
    {
        id:9,
        name: "Lugaw Plain",
        carbs : 3,
        fat : 8,
        protein : 6,
        calories : 110,
        imgURL : "lugaw_plain.jpg",
        cycling : 16,
        running : 11,
        cleaning : 40
    },
    {
        id:10,
        name: "Lugaw with Goto",
        carbs : 250,
        fat : 50,
        protein : 2,
        calories : 200,
        imgURL : "lugaw_goto.jpg",
        cycling : 37,
        running : 25,
        cleaning : 90
    },
    {
        id:11,
        name: "Pandesal",
        carbs : 18.2,
        fat : 2.2,
        protein : 3.3,
        calories : 108,
        imgURL : "pandesal.jpg",
        cycling : 17,
        running : 11,
        cleaning : 41
    },
    {
        id:12,
        name: "Sausage",
        carbs : 5,
        fat : 2.5,
        protein : 1.5,
        calories : 40,
        imgURL : "sausage.jpg",
        cycling : 6,
        running : 4,
        cleaning : 14
    },
    {
        id:13,
        name: "Scrambled Eggs",
        carbs : 0.6,
        fat : 5,
        protein : 6,
        calories : 70,
        imgURL : "scramble_eggs.jpg",
        cycling : 11,
        running : 7,
        cleaning : 27
    },
    {
        id:14,
        name: "Sinangag",
        carbs : 45.2,
        fat : 8.8,
        protein : 3.8,
        calories : 279,
        imgURL : "sinangag.jpg",
        cycling : 42,
        running : 28,
        cleaning : 130
    },
    {
        id:15,
        name: "Suman",
        carbs : 6.2,
        fat : 4.2,
        protein : 0.8,
        calories : 63,
        imgURL : "suman.jpg",
        cycling : 9,
        running : 6,
        cleaning : 23
    },
    {
        id:16,
        name: "Taho",
        carbs : 8,
        fat : 4,
        protein : 8,
        calories : 180,
        imgURL : "taho.jpg",
        cycling : 27,
        running : 18,
        cleaning : 70
    },
    {
        id:17,
        name: "Tapsilog",
        carbs : 50,
        fat : 7,
        protein : 20,
        calories : 364,
        imgURL : "tapsilog.jpg",
        cycling : 55,
        running : 37,
        cleaning : 140
    },
    {
        id:18,
        name: "Tocino",
        carbs : 10,
        fat : 19,
        protein : 16,
        calories : 280,
        imgURL : "tocino.jpg",
        cycling : 43,
        running : 28,
        cleaning : 220
    },
    {
        id:19,
        name: "Tortang Talong",
        carbs : 13,
        fat : 9,
        protein : 5,
        calories : 147,
        imgURL : "tortang_talong.jpg",
        cycling : 22,
        running : 15,
        cleaning : 54
    },
    {
        id:20,
        name: "Tuyo",
        carbs : 5,
        fat : 1.8,
        protein : 2,
        calories : 44,
        imgURL : "tuyo.jpg",
        cycling : 6,
        running : 4,
        cleaning : 16
    },
    {
        id:21,
        name: "Coffee",
        carbs : 4.5,
        fat : 1.7,
        protein : 0.4,
        calories : 34,
        imgURL : "coffee.jpg",
        cycling : 5,
        running : 3,
        cleaning : 12
    },
    {
        id:22,
        name: "Fried Egg",
        carbs : 0.3,
        fat : 6.5,
        protein : 5.4,
        calories : 83,
        imgURL : "fried_egg.jpg",
        cycling : 12,
        running : 8,
        cleaning : 30
    },
    {
        id:23,
        name: "White Rice",
        carbs : 39,
        fat : 1,
        protein : 4,
        calories : 181,
        imgURL : "white_rice.jpg",
        cycling : 27,
        running : 18,
        cleaning : 65
    },
    {
        id:24,
        name: "Wheat Bread",
        carbs : 15.5,
        fat : 1.3,
        protein : 4.4,
        calories : 91,
        imgURL : "wheat_bread.jpg",
        cycling : 14,
        running : 9,
        cleaning : 33
    },
    {
        id:25,
        name: "Spam",
        carbs : 1,
        fat : 16,
        protein : 7,
        calories : 180,
        imgURL : "spam.jpg",
        cycling : 27,
        running : 18,
        cleaning : 65
    },
    {
        id:26,
        name: "Itlog na Pula",
        carbs : 7,
        fat : 5.3,
        protein : 7.4,
        calories : 104,
        imgURL : "itlog_pula.jpg",
        cycling : 15,
        running : 10,
        cleaning : 38
    }
]

export default breakfastDB