const lunch_dinner_DB = [
    {
        id:1,
        name: "Adobo sa Gata",
        carbs : 0,
        fat : 15,
        protein : 40,
        calories : 300,
        imgURL : "adobo_gata.jpg",
        cycling : 40,
        running : 30,
        cleaning : 100
    },
    {
        id:2,
        name: "Adobong Baboy",
        carbs : 10.1,
        fat : 2.5,
        protein : 24,
        calories : 159,
        imgURL : "adobong_baboy.jpg",
        cycling : 24,
        running : 16,
        cleaning : 58
    },
    {
        id:3,
        name: "Adobong Kangkong",
        carbs : 21.7,
        fat : 3.5,
        protein : 5.9,
        calories : 142,
        imgURL : "adobong_kangkong.jpg",
        cycling : 21,
        running : 14,
        cleaning : 52
    },
    {
        id:4,
        name: "Adobong Manok",
        carbs : 5.2,
        fat : 5,
        protein : 26,
        calories : 190,
        imgURL : "adobong_manok.jpg",
        cycling : 29,
        running : 19,
        cleaning : 1.1
    },
    {
        id:5,
        name: "Adobong Pusit",
        carbs : 3,
        fat : 7,
        protein : 28,
        calories : 198,
        imgURL : "adobong_pusit.jpg",
        cycling : 20,
        running : 13,
        cleaning : 49
    },
    {
        id:6,
        name: "Adobong Sitaw",
        carbs : 15,
        fat : 5,
        protein : 12,
        calories : 158,
        imgURL : "adobong_sitaw.jpg",
        cycling : 24,
        running : 16,
        cleaning : 58
    },
    {
        id:7,
        name: "Afritada",
        carbs : 12,
        fat : 9,
        protein : 28,
        calories : 245,
        imgURL : "afritada.jpg",
        cycling : 37,
        running : 25,
        cleaning : 1.5
    },
    {
        id:8,
        name: "Bangus",
        carbs : 0,
        fat : 0,
        protein : 21,
        calories : 102,
        imgURL : "pritong_bangus.jpg",
        cycling : 15,
        running : 10,
        cleaning : 37
    },
    {
        id:9,
        name: "Batchoy",
        carbs : 4.4,
        fat : 26,
        protein : 16.7,
        calories : 322,
        imgURL : "batchoy.jpg",
        cycling : 49,
        running : 32,
        cleaning : 110
    },
    {
        id:10,
        name: "Bicol Express",
        carbs : 22,
        fat : 0,
        protein : 15,
        calories : 150,
        imgURL : "bicol_express.jpg",
        cycling : 23,
        running : 15,
        cleaning : 55
    },
    {
        id:11,
        name: "Bopis",
        carbs : 3.8,
        fat : 3.4,
        protein : 8.4,
        calories : 78,
        imgURL : "bopis.jpg",
        cycling : 11,
        running : 7,
        cleaning : 28
    },
    {
        id:12,
        name: "Bulalo",
        carbs : 0,
        fat : 26,
        protein : 24,
        calories : 342,
        imgURL : "bulalo.jpg",
        cycling : 52,
        running : 35,
        cleaning : 125
    },
    {
        id:13,
        name: "Burger Steak",
        carbs : 0,
        fat : 21,
        protein : 29,
        calories : 310,
        imgURL : "burger_steak.jpg",
        cycling : 47,
        running : 31,
        cleaning : 110
    },
    {
        id:14,
        name: "Chicken Inasal",
        carbs : 5,
        fat : 12,
        protein : 20,
        calories : 213,
        imgURL : "chicken_inasal.jpg",
        cycling : 32,
        running : 21,
        cleaning : 90
    },
    {
        id:15,
        name: "Chop Seuy",
        carbs : 0,
        fat : 3.1,
        protein : 26.7,
        calories : 142,
        imgURL : "chop_seuy.jpg",
        cycling : 21,
        running : 14,
        cleaning : 52
    },
    {
        id:16,
        name: "Crispy Pata",
        carbs : 14,
        fat : 432,
        protein : 76,
        calories : 812,
        imgURL : "crispy_pata.jpg",
        cycling : 120,
        running : 90,
        cleaning : 290
    },
    {
        id:17,
        name: "Dinuguan",
        carbs : 5.2,
        fat : 10.3,
        protein : 33.6,
        calories : 255,
        imgURL : "dinuguan.jpg",
        cycling : 39,
        running : 26,
        cleaning : 95
    },
    {
        id:18,
        name: "Fried Chicken Breast",
        carbs : 0,
        fat : 3.4,
        protein : 37.4,
        calories : 180,
        imgURL : "fried_chicken_breast.jpg",
        cycling : 27,
        running : 18,
        cleaning : 70
    },
    {
        id:19,
        name: "Fried Chicken Wings",
        carbs : 3.2,
        fat : 11.1,
        protein : 10.6,
        calories : 158,
        imgURL : "fried_chicken_wings.jpg",
        cycling : 24,
        running : 16,
        cleaning : 58
        
    },
    {
        id:20,
        name: "Fried Chicken Drumstick",
        carbs : 4,
        fat : 8,
        protein : 12,
        calories : 130,
        imgURL : "fried_chicken_drumstick.jpg",
        cycling : 19,
        running : 13,
        cleaning : 47
    },
    {
        id:21,
        name: "Fried Chicken Thigh",
        carbs : 7.8,
        fat : 14.2,
        protein : 18.6,
        calories : 238,
        imgURL : "fried_chicken_thighs.jpg",
        cycling : 30,
        running : 24,
        cleaning : 100
    },
    {
        id:22,
        name: "Hamunado",
        carbs : 4,
        fat : 12,
        protein : 6,
        calories : 130,
        imgURL : "hamunado.jpg",
        cycling : 19,
        running : 13,
        cleaning : 47
    },
    {
        id:23,
        name: "Inihaw na Liempo",
        carbs : 3,
        fat : 11,
        protein : 7,
        calories : 140,
        imgURL : "inihaw_liempo.jpg",
        cycling : 21,
        running : 14,
        cleaning : 51
    },
    {
        id:24,
        name: "Kaldereta",
        carbs : 15.4,
        fat : 16.7,
        protein :11.3,
        calories : 191,
        imgURL : "kaldereta.jpg",
        cycling : 23,
        running : 15,
        cleaning : 55
    },
    {
        id:25,
        name: "Kare-Kare",
        carbs : 22.5,
        fat : 28,
        protein : 25,
        calories : 360,
        imgURL : "kare-kare.jpg",
        cycling : 55,
        running : 36,
        cleaning : 125
    },
    {
        id:26,
        name: "Kinilaw",
        carbs : 1,
        fat : 12,
        protein : 10,
        calories : 155,
        imgURL : "kinilaw.jpg",
        cycling : 23,
        running : 15,
        cleaning : 57
    },
    {
        id:27,
        name: "Lechon",
        carbs : 0,
        fat : 13.9,
        protein : 27.3,
        calories : 242,
        imgURL : "lechon.jpg",
        cycling : 37,
        running : 24,
        cleaning : 75
    },
    {
        id:28,
        name: "Lechon Kawali",
        carbs : 3.2,
        fat : 26.9,
        protein : 18.1,
        calories : 322,
        imgURL : "lechon_kawali.jpg",
        cycling : 49,
        running : 32,
        cleaning : 110
    },
    {
        id:29,
        name: "Longsilog",
        carbs : 56,
        fat : 29,
        protein :17,
        calories : 550,
        imgURL : "longsilog.jpg",
        cycling : 80,
        running : 56,
        cleaning : 190
        
    },
    {
        id:30,
        name: "Lumpiang Prito",
        carbs : 12.1,
        fat : 12.9,
        protein : 10.9,
        calories : 207,
        imgURL : "lumpiang_prito.jpg",
        cycling : 31,
        running : 21,
        cleaning : 80
    },
    {
        id:31,
        name: "Lumpiang Sariwa",
        carbs : 11.6,
        fat : 4.4,
        protein : 3.1,
        calories : 99,
        imgURL : "lumpiang_sariwa.jpg",
        cycling : 15,
        running : 10,
        cleaning : 36
    },
    {
        id:32,
        name: "Mechado",
        carbs : 4.5,
        fat : 14,
        protein : 20.6,
        calories : 230,
        imgURL : "mechado.jpg",
        cycling : 35,
        running : 23,
        cleaning : 100
    },
    {
        id:33,
        name: "Munggo",
        carbs : 26,
        fat : 6,
        protein : 20,
        calories : 234,
        imgURL : "munggo.jpg",
        cycling : 35,
        running : 23,
        cleaning : 100
    },
    {
        id:34,
        name: "Nilagang Baboy",
        carbs : 21,
        fat : 11,
        protein : 18,
        calories : 258,
        imgURL : "nilagang_baboy.jpg",
        cycling : 39,
        running : 26,
        cleaning : 110
    },
    {
        id:35,
        name: "Nilagang Baka",
        carbs : 17,
        fat : 9.8,
        protein : 32.3,
        calories : 222,
        imgURL : "nilagang_baka.jpg",
        cycling : 34,
        running : 22,
        cleaning : 90
    },
    {
        id:36,
        name: "Okoy Dilis",
        carbs : 20.9,
        fat : 6.2,
        protein : 6.2,
        calories : 166,
        imgURL : "okoy_dilis.jpg",
        cycling : 25,
        running : 16,
        cleaning : 60
    },
    {
        id:37,
        name: "Okoy Hipon",
        carbs : 23,
        fat : 7,
        protein : 17,
        calories : 225,
        imgURL : "okoy_hipon.jpg",
        cycling : 34,
        running : 23,
        cleaning : 90
    },
    {
        id:38,
        name: "Paksiw",
        carbs : 10,
        fat : 12,
        protein : 13,
        calories : 197,
        imgURL : "paksiw.jpg",
        cycling : 30,
        running : 20,
        cleaning : 80
    },
    {
        id:39,
        name: "Papaitan",
        carbs : 0,
        fat : 13.7,
        protein : 6.7,
        calories : 152,
        imgURL : "papaitan.jpg",
        cycling : 23,
        running : 15,
        cleaning : 56
    },
    {
        id:40,
        name: "Pinakbet",
        carbs : 11.1,
        fat : 5.5,
        protein : 2.7,
        calories : 98,
        imgURL : "pinakbet.jpg",
        cycling : 10,
        running : 10,
        cleaning : 36
    },
    {
        id:41,
        name: "Pork BBQ",
        carbs : 64.7,
        fat : 9.5,
        protein : 26.8,
        calories : 454,
        imgURL : "pork_bbq.jpg",
        cycling : 50,
        running : 33,
        cleaning : 120
        
    },
    {
        id:42,
        name: "Pork Chop",
        carbs : 0,
        fat : 9,
        protein : 23,
        calories : 160,
        imgURL : "pork_chop.jpg",
        cycling : 24,
        running : 16,
        cleaning : 58
    },
    {
        id:43,
        name: "Pork Sisig",
        carbs : 10.9,
        fat : 6.4,
        protein : 45.3,
        calories : 293,
        imgURL : "pork_sisig.jpg",
        cycling : 40,
        running : 30,
        cleaning : 140
    },
    {
        id:44,
        name: "Sardinas",
        carbs : 3,
        fat : 8,
        protein : 22,
        calories : 170,
        imgURL : "sardinas.jpg",
        cycling : 26,
        running : 17,
        cleaning : 60
    },
    {
        id:45,
        name: "Shanghai",
        carbs : 3.2,
        fat : 0,
        protein : 0,
        calories : 69,
        imgURL : "shanghai.jpg",
        cycling : 10,
        running : 7,
        cleaning : 25
    },
    {
        id:46,
        name: "Sinigang na Baboy",
        carbs : 6.3,
        fat : 2.5,
        protein : 25,
        calories : 153,
        imgURL : "sinigang_na_baboy.jpg",
        cycling : 23,
        running : 15,
        cleaning : 56
    },
    {
        id:47,
        name: "Sinigang na Bangus",
        carbs : 1,
        fat : 1,
        protein : 21,
        calories : 168,
        imgURL : "sinigang_na_bangus.jpg",
        cycling : 25,
        running : 15,
        cleaning : 60
    },
    {
        id:48,
        name: "Sinigang na Hipon",
        carbs : 12,
        fat : 2,
        protein : 21,
        calories : 148,
        imgURL : "sinigang_na_hipon.jpg",
        cycling : 22,
        running : 15,
        cleaning : 54
    },
    {
        id:49,
        name: "Tapsilog",
        carbs : 50,
        fat : 7,
        protein : 20,
        calories : 364,
        imgURL : "tapsilog.jpg",
        cycling : 55,
        running : 37,
        cleaning : 140
    },
    {
        id:50,
        name: "Tinapa",
        carbs : 38,
        fat : 0,
        protein : 0,
        calories : 152,
        imgURL : "tinapa.jpg",
        cycling : 23,
        running : 15,
        cleaning : 56
    },
    {
        id:51,
        name: "Tinola",
        carbs : 8.8,
        fat : 15.3,
        protein : 29,
        calories : 286,
        imgURL : "tinola.jpg",
        cycling : 35,
        running : 23,
        cleaning : 100
    },
    {
        id:52,
        name: "Tocilog",
        carbs : 23.4,
        fat : 6.4,
        protein : 31.1,
        calories : 283,
        imgURL : "tocilog.jpg",
        cycling : 43,
        running : 28,
        cleaning : 130
    },
    {
        id:53,
        name: "Tokwa't Baboy",
        carbs : 12,
        fat : 21,
        protein : 17,
        calories : 312,
        imgURL : "tokwat_baboy.jpg",
        cycling : 47,
        running : 31,
        cleaning : 110
    },
    {
        id:54,
        name: "White Rice",
        carbs : 39,
        fat : 1,
        protein : 4,
        calories : 181,
        imgURL : "white_rice.jpg",
        cycling : 27,
        running : 18,
        cleaning : 65
    },
    {
        id:55,
        name: "Tilapia",
        carbs : 0,
        fat : 2.5,
        protein : 20,
        calories : 100,
        imgURL : "tilapia.jpg",
        cycling : 15,
        running : 10,
        cleaning : 36
    },
    {
        id:56,
        name: "Pork Steak",
        carbs : 0,
        fat : 18,
        protein : 18,
        calories : 240,
        imgURL : "pork_steak.jpg",
        cycling : 36,
        running : 24,
        cleaning : 100
    },
    {
        id:57,
        name: "Ginisang Ampalaya",
        carbs : 27,
        fat : 2.5,
        protein : 2,
        calories : 140,
        imgURL : "ampalaya.jpg",
        cycling : 21,
        running : 14,
        cleaning : 51
    },
    {
        id:58,
        name: "Spaghetti",
        carbs : 45,
        fat : 12,
        protein : 10,
        calories : 340,
        imgURL : "spaghetti.jpg",
        cycling : 47,
        running : 31,
        cleaning : 110
    },
    {
        id:59,
        name: "Century Tuna",
        carbs : 1,
        fat : 5,
        protein : 9,
        calories : 90,
        imgURL : "century.jpg",
        cycling : 13,
        running : 9,
        cleaning : 33
    },
    {
        id:60,
        name: "Burger",
        carbs : 33,
        fat : 9,
        protein : 10,
        calories : 250,
        imgURL : "burger.jpg",
        cycling : 36,
        running : 24,
        cleaning : 100
    }
]

export default lunch_dinner_DB